// Auto-generated from Comparison-Commercial_EV_Chargers.xlsx — do not hand-edit structure, regenerate instead.
import type { CommercialCharger } from "./charger-types";

export const commercialChargers: CommercialCharger[] = [
  {
    id: `com-ocular-iq-commercial-iq-commercial-7kw`,
    photoUrl: `/images/chargers/ocular-iq-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Ocular IQ Commercial`,
    variant: `IQ Commercial 7kW`,
    price: 1800,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Car parks, workplaces, councils, schools, fleet depots, public charging`,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `China`,
    dimensions: `300 x 450 x 160 mm`,
    weight: `8.5 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `Untethered`,
    display: `Large LCD screen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / pay-per-use via backend`,
    ipRating: `IP65`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Heavy-duty metallic frame. Purpose-built for public/fleet applications. Distributed by EVSE Australia.`,
  },
  {
    id: `com-ocular-iq-commercial-iq-commercial-22kw`,
    photoUrl: `/images/chargers/ocular-iq-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Ocular IQ Commercial`,
    variant: `IQ Commercial 22kW`,
    price: 2200,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Car parks, workplaces, councils, schools, fleet depots, public charging`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `China`,
    dimensions: `300 x 450 x 160 mm`,
    weight: `8.5 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `Untethered`,
    display: `Large LCD screen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / pay-per-use via backend`,
    ipRating: `IP65`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Heavy-duty metallic frame. Purpose-built for public/fleet applications. Distributed by EVSE Australia.`,
  },
  {
    id: `com-ocular-iq-dual-tower-iq-dual-tower-22kw`,
    photoUrl: `/images/chargers/ocular-iq-dual-tower.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Ocular IQ Dual Tower`,
    variant: `IQ Dual Tower 22kW`,
    price: null,
    priceDisplay: `POA`,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Public car parks, shopping centres, councils, hospitality, apartment complexes`,
    phase: `Three`,
    power: `22 kW per port (44 kW total)`,
    ratedCurrent: `32A per port`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `China`,
    dimensions: `400 x 1500 x 200 mm (floor pedestal)`,
    weight: `~35 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `Untethered`,
    display: `Large LCD screen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / pay-per-use`,
    ipRating: `IP65`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Floor-standing dual-port tower. Charges 2 vehicles simultaneously. Ideal for high-volume public sites.`,
  },
  {
    id: `com-wallbox-commander-2-commander-2-single-phase`,
    photoUrl: `/images/chargers/wallbox-commander-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Wallbox Commander 2`,
    variant: `Commander 2 Single Phase`,
    price: 2200,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, hospitality, car parks, government, education, apartment buildings`,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m or 7m)`,
    countryOfManufacture: `Spain`,
    dimensions: `258 x 374 x 140 mm`,
    weight: `5.2 kg`,
    accessMethod: `RFID, app (myWallbox), PIN, password`,
    multiUser: true,
    cableLength: `5m or 7m tethered`,
    display: `7-inch LCD touchscreen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / myWallbox pay system`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Business-focused AC charger with built-in 4G SIM and revenue stream activation via myWallbox Business. Widely used across Australian commercial sites.`,
  },
  {
    id: `com-wallbox-commander-2-commander-2-three-phase`,
    photoUrl: `/images/chargers/wallbox-commander-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Wallbox Commander 2`,
    variant: `Commander 2 Three Phase`,
    price: 2800,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, hospitality, car parks, government, education, apartment buildings`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m or 7m)`,
    countryOfManufacture: `Spain`,
    dimensions: `258 x 374 x 140 mm`,
    weight: `5.2 kg`,
    accessMethod: `RFID, app (myWallbox), PIN, password`,
    multiUser: true,
    cableLength: `5m or 7m tethered`,
    display: `7-inch LCD touchscreen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / myWallbox pay system`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Business-focused AC charger with built-in 4G SIM and revenue stream activation via myWallbox Business. Widely used across Australian commercial sites.`,
  },
  {
    id: `com-schneider-evlink-pro-ac-evlink-pro-ac-7-4kw-single-phase`,
    photoUrl: `/images/chargers/schneider-evlink-pro-ac.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Schneider EVlink Pro AC`,
    variant: `EVlink Pro AC 7.4kW Single Phase`,
    price: 1200,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Commercial buildings, fleet depots, apartment blocks, government, corporate car parks`,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered cable (model dependent)`,
    countryOfManufacture: `China`,
    dimensions: `230 x 360 x 140 mm`,
    weight: `4.5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `Untethered (socket) or tethered (model dependent)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `3rd-gen commercial AC charger. SOCCI cybersecurity compliant. Widely used in managed car parks and fleet sites. Pedestal options available.`,
  },
  {
    id: `com-schneider-evlink-pro-ac-evlink-pro-ac-22kw-three-phase`,
    photoUrl: `/images/chargers/schneider-evlink-pro-ac.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Schneider EVlink Pro AC`,
    variant: `EVlink Pro AC 22kW Three Phase`,
    price: 1600,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Commercial buildings, fleet depots, apartment blocks, government, corporate car parks`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered cable (model dependent)`,
    countryOfManufacture: `China`,
    dimensions: `230 x 360 x 140 mm`,
    weight: `4.5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `Untethered (socket) or tethered (model dependent)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `3rd-gen commercial AC charger. SOCCI cybersecurity compliant. Widely used in managed car parks and fleet sites. Pedestal options available.`,
  },
  {
    id: `com-autel-maxicharger-ac-wallbox-commercial-ac-wallbox-single-phase`,
    photoUrl: `/images/chargers/autel-ac-wallbox-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Autel MaxiCharger AC Wallbox (Commercial)`,
    variant: `AC Wallbox Single Phase`,
    price: 968,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, light commercial, apartment buildings, fleet, government sites`,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `China`,
    dimensions: `235 x 190 x 56 mm`,
    weight: `1.8 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Compact and cost-effective. Suitable for light commercial rollouts. Supported locally by JET Charge Australia.`,
  },
  {
    id: `com-autel-maxicharger-ac-wallbox-commercial-ac-wallbox-three-phase`,
    photoUrl: `/images/chargers/autel-ac-wallbox-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Autel MaxiCharger AC Wallbox (Commercial)`,
    variant: `AC Wallbox Three Phase`,
    price: 1479,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, light commercial, apartment buildings, fleet, government sites`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `China`,
    dimensions: `235 x 190 x 56 mm`,
    weight: `1.8 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Compact and cost-effective. Suitable for light commercial rollouts. Supported locally by JET Charge Australia.`,
  },
  {
    id: `com-teltonika-teltocharge-commercial-evc-110-11kw`,
    photoUrl: `/images/chargers/teltonika-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Teltonika TeltoCharge Commercial`,
    variant: `EVC 110 (11kW)`,
    price: 1750,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Government, councils, corporate car parks, schools, fleet, apartment buildings`,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `Lithuania`,
    dimensions: `170 x 341 x 94 mm`,
    weight: `2.8 kg`,
    accessMethod: `RFID card authorisation`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `No display (LED status only)`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `European-built with strong cybersecurity and remote management capability. Popular in government/council deployments.`,
  },
  {
    id: `com-teltonika-teltocharge-commercial-evc-120-22kw`,
    photoUrl: `/images/chargers/teltonika-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Teltonika TeltoCharge Commercial`,
    variant: `EVC 120 (22kW)`,
    price: 2000,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Government, councils, corporate car parks, schools, fleet, apartment buildings`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `Lithuania`,
    dimensions: `170 x 341 x 94 mm`,
    weight: `2.8 kg`,
    accessMethod: `RFID card authorisation`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `No display (LED status only)`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `European-built with strong cybersecurity and remote management capability. Popular in government/council deployments.`,
  },
  {
    id: `com-smappee-ev-wall-commercial-ev-wall-single-phase`,
    photoUrl: `/images/chargers/smappee-ev-wall-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Smappee EV Wall (Commercial)`,
    variant: `EV Wall Single Phase`,
    price: 1729,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, apartment buildings, hospitality, commercial buildings`,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (8m)`,
    countryOfManufacture: `Belgium`,
    dimensions: `300 x 300 x 110 mm`,
    weight: `9.8 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `8m tethered`,
    display: `No display (LED)`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / fleet billing`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Belgian-made with strong energy monitoring and fleet management. Integrates with Smappee energy management systems.`,
  },
  {
    id: `com-smappee-ev-wall-commercial-ev-wall-three-phase`,
    photoUrl: `/images/chargers/smappee-ev-wall-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Smappee EV Wall (Commercial)`,
    variant: `EV Wall Three Phase`,
    price: 2229,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, apartment buildings, hospitality, commercial buildings`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (8m)`,
    countryOfManufacture: `Belgium`,
    dimensions: `300 x 300 x 110 mm`,
    weight: `9.8 kg`,
    accessMethod: `RFID card, app`,
    multiUser: true,
    cableLength: `8m tethered`,
    display: `No display (LED)`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / fleet billing`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Belgian-made with strong energy monitoring and fleet management. Integrates with Smappee energy management systems.`,
  },
  {
    id: `com-evos-fleet22-fleet22`,
    photoUrl: `/images/chargers/evos-fleet22.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `EVOS Fleet22`,
    variant: `Fleet22`,
    price: 1800,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Fleet depots, government, councils, schools, apartment buildings, workplaces`,
    phase: `Both`,
    power: `7–22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m or 6m)`,
    countryOfManufacture: `Australia`,
    dimensions: `380 x 100 mm`,
    weight: `6.5 kg`,
    accessMethod: `App / VID lock to authorised user`,
    multiUser: true,
    cableLength: `5m or 6m tethered`,
    display: `LED colour status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `App / fleet management billing`,
    ipRating: `IP65`,
    operatingTemp: `-25°C to +55°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Australian-made. Designed for fleet and commercial use. Supports tariff scheduling, load balancing and solar-only mode. Strong local support.`,
  },
  {
    id: `com-weidmuller-ac-smart-commercial-ch-w-s-a11-p-11kw`,
    photoUrl: `/images/chargers/weidmuller-ac-smart.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Weidmuller AC SMART (Commercial)`,
    variant: `CH-W-S-A11-P (11kW)`,
    price: 1600,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Corporate buildings, government, fleet, car parks, commercial properties`,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m, 7m or 10m options)`,
    countryOfManufacture: `Germany`,
    dimensions: `268 x 433 x 150 mm`,
    weight: `5.1 kg`,
    accessMethod: `RFID (Value & Advanced models)`,
    multiUser: true,
    cableLength: `5m, 7m or 10m options`,
    display: `No display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `German-engineered. Three tiers (Basic/Value/Advanced) with scalable smart features. Good fit for managed commercial car parks.`,
  },
  {
    id: `com-weidmuller-ac-smart-commercial-ch-w-s-a22-p-22kw`,
    photoUrl: `/images/chargers/weidmuller-ac-smart.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Weidmuller AC SMART (Commercial)`,
    variant: `CH-W-S-A22-P (22kW)`,
    price: 1800,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Corporate buildings, government, fleet, car parks, commercial properties`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m, 7m or 10m options)`,
    countryOfManufacture: `Germany`,
    dimensions: `268 x 433 x 150 mm`,
    weight: `5.1 kg`,
    accessMethod: `RFID (Value & Advanced models)`,
    multiUser: true,
    cableLength: `5m, 7m or 10m options`,
    display: `No display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `German-engineered. Three tiers (Basic/Value/Advanced) with scalable smart features. Good fit for managed commercial car parks.`,
  },
  {
    id: `com-abb-terra-ac-commercial-terra-ac-w11`,
    photoUrl: `/images/chargers/abb-terra-ac-commercial-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ABB Terra AC (Commercial)`,
    variant: `Terra AC W11`,
    price: 2300,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Commercial buildings, car parks, hospitality, fleet, government, universities`,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m or 7.6m)`,
    countryOfManufacture: `Italy`,
    dimensions: `320 x 195 x 110 mm`,
    weight: `6.5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `5m or 7.6m tethered`,
    display: `LCD display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing / credit card (model dependent)`,
    ipRating: `IP54`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Global ABB brand with strong Australian distribution. Suited for professional commercial and fleet installations.`,
  },
  {
    id: `com-abb-terra-ac-commercial-terra-ac-w22`,
    photoUrl: `/images/chargers/abb-terra-ac-commercial-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ABB Terra AC (Commercial)`,
    variant: `Terra AC W22`,
    price: 2400,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Commercial buildings, car parks, hospitality, fleet, government, universities`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m or 7.6m)`,
    countryOfManufacture: `Italy`,
    dimensions: `320 x 195 x 110 mm`,
    weight: `6.5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `5m or 7.6m tethered`,
    display: `LCD display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing / credit card (model dependent)`,
    ipRating: `IP54`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Global ABB brand with strong Australian distribution. Suited for professional commercial and fleet installations.`,
  },
  {
    id: `com-enphase-iq-ev-charger-2-iq-evse-eu-3032-0105-1300`,
    photoUrl: `/images/chargers/enphase-iq2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Enphase IQ EV Charger 2`,
    variant: `IQ-EVSE-EU-3032-0105-1300`,
    price: 2048,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, light commercial, solar-integrated sites, fleet`,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (7.5m)`,
    countryOfManufacture: `TBD`,
    dimensions: `370 x 250 x 118 mm`,
    weight: `11 kg`,
    accessMethod: `App-based`,
    multiUser: true,
    cableLength: `7.5m tethered`,
    display: `LED`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `App / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-40°C to +55°C`,
    bidirectional: true,
    bidirectionalNote: `V2X capable (software unlock required)`,
    warrantyYears: `5 years`,
    notes: `Longest warranty on the market. Integrates seamlessly with Enphase solar/battery ecosystem. V2X capability is a future differentiator.`,
  },
  {
    id: `com-tritium-rtm75-rtm75-dual-ccs2`,
    photoUrl: `/images/chargers/tritium-rtm75.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Tritium RTM75`,
    variant: `RTM75 Dual CCS2`,
    price: null,
    priceDisplay: `POA (approx. $25,000–$35,000 installed)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Public car parks, petrol/service stations, retail destinations, councils, highways, fleet depots`,
    phase: `Three`,
    power: `75 kW`,
    ratedCurrent: `200A (CCS2)`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `CCS2 + CCS2, or CCS2 + CHAdeMO (6m cables)`,
    countryOfManufacture: `Australia (Brisbane)`,
    dimensions: `560 x 1620 x 330 mm`,
    weight: `170 kg`,
    accessMethod: `Plug & Charge (ISO 15118), RFID, app, contactless payment`,
    multiUser: true,
    cableLength: `6m cables per port`,
    display: `10-inch LCD display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, app, Plug & Charge`,
    ipRating: `IP65`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Australian-made in Brisbane. The top-selling DC fast charger globally. Used by NRMA, Evie, Chargefox, Queensland Electric Highway. Liquid-cooled, modular design for easy servicing.`,
  },
  {
    id: `com-tritium-rtm75-rtm75-ccs2-chademo`,
    photoUrl: `/images/chargers/tritium-rtm75.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Tritium RTM75`,
    variant: `RTM75 CCS2 + CHAdeMO`,
    price: null,
    priceDisplay: `POA (approx. $25,000–$35,000 installed)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Public car parks, petrol/service stations, retail destinations, councils, highways, fleet depots`,
    phase: `Three`,
    power: `75 kW`,
    ratedCurrent: `200A (CCS2)`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `CCS2 + CCS2, or CCS2 + CHAdeMO (6m cables)`,
    countryOfManufacture: `Australia (Brisbane)`,
    dimensions: `560 x 1620 x 330 mm`,
    weight: `170 kg`,
    accessMethod: `Plug & Charge (ISO 15118), RFID, app, contactless payment`,
    multiUser: true,
    cableLength: `6m cables per port`,
    display: `10-inch LCD display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, app, Plug & Charge`,
    ipRating: `IP65`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Australian-made in Brisbane. The top-selling DC fast charger globally. Used by NRMA, Evie, Chargefox, Queensland Electric Highway. Liquid-cooled, modular design for easy servicing.`,
  },
  {
    id: `com-kempower-s-series-s-series-150kw-400kw-scalable-satellite-system`,
    photoUrl: `/images/chargers/kempower-s-series.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Kempower S-Series`,
    variant: `S-Series 150kW–400kW (scalable satellite system)`,
    price: null,
    priceDisplay: `POA (contact supplier)`,
    chargerType: `DC Fast Charger (scalable hub+satellite)`,
    suitableApplications: `Highways, petrol/service stations, large car parks, fleet depots, transit hubs`,
    phase: `Three`,
    power: `150 kW – 400 kW per cabinet (dynamically shared across up to 8 connectors)`,
    ratedCurrent: `Up to 500A`,
    numberOfPorts: `Up to 8 per cabinet (satellite dispensers)`,
    connectorType: `CCS2 (5m spring-loaded cables)`,
    countryOfManufacture: `Finland`,
    dimensions: `Cabinet: 800 x 1900 x 600 mm
Satellite: 250 x 1500 x 200 mm`,
    weight: `Cabinet: ~450 kg`,
    accessMethod: `Plug & Charge, RFID, contactless payment (QR code)`,
    multiUser: true,
    cableLength: `5m spring-loaded cables per satellite`,
    display: `7-inch touchscreen per satellite`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Plug & Charge, QR code`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Hub-and-satellite architecture maximises power efficiency. Used by Evie Networks across Australia. Scales easily as demand grows.`,
  },
  {
    id: `com-abb-terra-360-terra-360-up-to-360kw-4-connectors`,
    photoUrl: `/images/chargers/abb-terra-360.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ABB Terra 360`,
    variant: `Terra 360 (up to 360kW, 4 connectors)`,
    price: null,
    priceDisplay: `POA (approx. $40,000–$60,000 installed)`,
    chargerType: `DC Fast Charger (ultra-rapid)`,
    suitableApplications: `Petrol/service stations, motorway hubs, high-traffic retail, transit centres`,
    phase: `Three`,
    power: `Up to 360 kW (dynamically shared across up to 4 connectors)`,
    ratedCurrent: `Up to 900A`,
    numberOfPorts: `Up to 4 connectors`,
    connectorType: `CCS2 (all 4 connectors)`,
    countryOfManufacture: `Italy (ABB Group)`,
    dimensions: `760 x 1870 x 470 mm`,
    weight: `~500 kg`,
    accessMethod: `Plug & Charge (ISO 15118), RFID, contactless payment`,
    multiUser: true,
    cableLength: `Cable length options vary`,
    display: `10-inch colour touchscreen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Plug & Charge, contactless`,
    ipRating: `IP54`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Adds 100km range in under 3 minutes at peak. ABB's flagship ultra-rapid charger. Widely deployed globally. Suitable for high-throughput petrol station replacement or roadside hubs.`,
  },
  {
    id: `com-abb-terra-124-terra124-dc-120kw-2-connectors`,
    photoUrl: `/images/chargers/abb-terra-124.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ABB Terra 124`,
    variant: `Terra124 DC (120kW, 2 connectors)`,
    price: null,
    priceDisplay: `POA (approx. $20,000–$30,000 installed)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Car parks, retail destinations, workplaces, councils, fleet depots, petrol stations`,
    phase: `Three`,
    power: `120 kW continuous (up to 60 kW per port)`,
    ratedCurrent: `Up to 350A`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `CCS2 + CCS2`,
    countryOfManufacture: `Italy (ABB Group)`,
    dimensions: `670 x 1820 x 385 mm`,
    weight: `~300 kg`,
    accessMethod: `RFID, Plug & Charge, contactless payment`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `7-inch touchscreen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Plug & Charge`,
    ipRating: `IP54`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Mid-range DC fast charger well-suited to Australian car parks and destination charging. Proven ABB reliability. Available via EVSE Australia.`,
  },
  {
    id: `com-autel-maxicharger-dc-compact-dc-compact-50kw-pedestal`,
    photoUrl: `/images/chargers/autel-dc-compact.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Autel MaxiCharger DC Compact`,
    variant: `DC Compact 50kW (Pedestal)`,
    price: null,
    priceDisplay: `POA (approx. $15,000–$20,000 installed)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Petrol/service stations, retail car parks, fleet depots, councils, hospitality`,
    phase: `Three`,
    power: `50 kW`,
    ratedCurrent: `125A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `CCS2 + CHAdeMO or CCS2 + CCS2 (5.5m cables)`,
    countryOfManufacture: `China`,
    dimensions: `390 x 1590 x 380 mm`,
    weight: `~150 kg`,
    accessMethod: `RFID, Plug & Charge, credit card reader`,
    multiUser: true,
    cableLength: `5.5m tethered cables`,
    display: `7-inch HD touchscreen`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Plug & Charge, contactless`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Entry-level DC fast charger from Autel. Provides ~130km range from a 30-minute charge. Small footprint. Supported locally by JET Charge Australia.`,
  },
  {
    id: `com-autel-maxicharger-dc-fast-dc-fast-60kw-240kw`,
    photoUrl: `/images/chargers/autel-dc-fast.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Autel MaxiCharger DC Fast`,
    variant: `DC Fast 60kW–240kW`,
    price: null,
    priceDisplay: `POA (contact supplier)`,
    chargerType: `DC Fast Charger (high power)`,
    suitableApplications: `Petrol/service stations, highways, fleet depots, large retail, transit hubs`,
    phase: `Three`,
    power: `60 kW – 240 kW (configurable)`,
    ratedCurrent: `Up to 600A`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `CCS2 + CHAdeMO or CCS2 + CCS2`,
    countryOfManufacture: `China`,
    dimensions: `~800 x 1900 x 500 mm`,
    weight: `~400 kg`,
    accessMethod: `RFID, Plug & Charge (ISO 15118), credit card, Apple Pay, Google Pay`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `27-inch 4K touchscreen (advertising capability)`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Apple Pay, Google Pay, Plug & Charge`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Adds 260km range in 10 minutes at 240kW. Features a 27" 4K advertising screen for CPO revenue. Designed for high-throughput public charging hubs.`,
  },
  {
    id: `com-sigenergy-sigenstor-evdc-sigenstor-evdc-12-5kw`,
    photoUrl: `/images/chargers/sigenergy-sigenstor-evdc.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Sigenergy Sigenstor EVDC`,
    variant: `SigenStor EVDC 12.5kW`,
    price: 6700,
    priceDisplay: null,
    chargerType: `DC Fast Charger (integrated)`,
    suitableApplications: `Residential+commercial hybrid, fleet depots, workplaces with Sigenergy systems`,
    phase: `Both`,
    power: `12.5 kW`,
    ratedCurrent: `40A`,
    numberOfPorts: `1`,
    connectorType: `CCS2 (5m / 7.5m cables)`,
    countryOfManufacture: `China`,
    dimensions: `700 x 270 x 260 mm`,
    weight: `40 kg`,
    accessMethod: `RFID`,
    multiUser: true,
    cableLength: `5m or 7.5m tethered`,
    display: `LED`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP66`,
    operatingTemp: `-30°C to +60°C`,
    bidirectional: true,
    warrantyYears: `3 years`,
    notes: `Must be paired with Sigenergy Controller (inverter/battery system). Unique V2G/V2H capability. IP66 – highest weatherproofing in class.`,
  },
  {
    id: `com-sigenergy-sigenstor-evdc-sigenstor-evdc-25kw`,
    photoUrl: `/images/chargers/sigenergy-sigenstor-evdc.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Sigenergy Sigenstor EVDC`,
    variant: `SigenStor EVDC 25kW`,
    price: 8600,
    priceDisplay: null,
    chargerType: `DC Fast Charger (integrated)`,
    suitableApplications: `Residential+commercial hybrid, fleet depots, workplaces with Sigenergy systems`,
    phase: `Both`,
    power: `25 kW`,
    ratedCurrent: `80A`,
    numberOfPorts: `1`,
    connectorType: `CCS2 (5m / 7.5m cables)`,
    countryOfManufacture: `China`,
    dimensions: `700 x 270 x 260 mm`,
    weight: `40 kg`,
    accessMethod: `RFID`,
    multiUser: true,
    cableLength: `5m or 7.5m tethered`,
    display: `LED`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP66`,
    operatingTemp: `-30°C to +60°C`,
    bidirectional: true,
    warrantyYears: `3 years`,
    notes: `Must be paired with Sigenergy Controller (inverter/battery system). Unique V2G/V2H capability. IP66 – highest weatherproofing in class.`,
  },
  {
    id: `com-schneider-evlink-pro-dc-180-evlink-pro-dc-180kw`,
    photoUrl: `/images/chargers/schneider-evlink-pro-dc-180.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Schneider EVlink Pro DC 180`,
    variant: `EVlink Pro DC 180kW`,
    price: null,
    priceDisplay: `POA (contact supplier)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Fleet depots, petrol stations, highway corridors, commercial buildings`,
    phase: `Three`,
    power: `Up to 180 kW`,
    ratedCurrent: `Up to 500A`,
    numberOfPorts: `2 (dual port)`,
    connectorType: `CCS2 + CCS2`,
    countryOfManufacture: `France (Schneider)`,
    dimensions: `~800 x 1900 x 600 mm`,
    weight: `~400 kg`,
    accessMethod: `RFID, Plug & Charge, contactless payment`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `Touchscreen display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, Plug & Charge`,
    ipRating: `IP55`,
    operatingTemp: `-35°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `High-power DC from a global energy management leader. Maximises uptime with advanced diagnostics. Used at fleet depots and commercial highway sites.`,
  },
  {
    id: `com-keba-kecontact-p30-x-series-p30-x-series-7-4kw`,
    photoUrl: `/images/chargers/keba-p30-x-series.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `KEBA KeContact P30 X-Series`,
    variant: `P30 X-Series 7.4kW`,
    price: 1750,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, car parks, government, hospitality, universities, car dealerships`,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered (4m or 6m)`,
    countryOfManufacture: `Austria`,
    dimensions: `322 x 130 x 110 mm`,
    weight: `2.1 kg`,
    accessMethod: `RFID / NFC card`,
    multiUser: true,
    cableLength: `4m or 6m tethered or untethered`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Austrian-made, carbon-neutral manufacture. Only wallbox worldwide with VDE certificate. Over 100,000 units sold globally. DC leakage detection built-in eliminates need for Type B RCD upstream. Distributed by EVSE Australia.`,
  },
  {
    id: `com-keba-kecontact-p30-x-series-p30-x-series-22kw`,
    photoUrl: `/images/chargers/keba-p30-x-series.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `KEBA KeContact P30 X-Series`,
    variant: `P30 X-Series 22kW`,
    price: 1850,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, car parks, government, hospitality, universities, car dealerships`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered (4m or 6m)`,
    countryOfManufacture: `Austria`,
    dimensions: `322 x 130 x 110 mm`,
    weight: `2.1 kg`,
    accessMethod: `RFID / NFC card`,
    multiUser: true,
    cableLength: `4m or 6m tethered or untethered`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP54`,
    operatingTemp: `-25°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    notes: `Austrian-made, carbon-neutral manufacture. Only wallbox worldwide with VDE certificate. Over 100,000 units sold globally. DC leakage detection built-in eliminates need for Type B RCD upstream. Distributed by EVSE Australia.`,
  },
  {
    id: `com-eo-genius-2-eo-genius-2-single-phase-7-2kw`,
    photoUrl: `/images/chargers/eo-genius-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `EO Genius 2`,
    variant: `EO Genius 2 Single Phase (7.2kW)`,
    price: null,
    priceDisplay: `POA (contact distributor)`,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Fleet depots, workplaces, offices, hospitals, schools, hospitality, apartment buildings`,
    phase: `Single`,
    power: `7.2 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered cable`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `210 x 290 x 110 mm`,
    weight: `3.2 kg`,
    accessMethod: `RFID card (EO branded RFID tags available)`,
    multiUser: true,
    cableLength: `Socket or tethered (model dependent)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / fleet billing via EO Cloud`,
    ipRating: `IP55`,
    operatingTemp: `-25°C to +50°C`,
    bidirectional: true,
    bidirectionalNote: `V2G-ready (hardware upgrade available)`,
    warrantyYears: `3 years`,
    notes: `Purpose-built commercial charger. MID-certified energy meter standard. V2G-ready via hardware upgrade — future-proof for vehicle-to-grid use. Pairs with EO Hub 2 for unlimited scalable fleet management.`,
  },
  {
    id: `com-eo-genius-2-eo-genius-2-three-phase-22kw`,
    photoUrl: `/images/chargers/eo-genius-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `EO Genius 2`,
    variant: `EO Genius 2 Three Phase (22kW)`,
    price: null,
    priceDisplay: `POA (contact distributor)`,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Fleet depots, workplaces, offices, hospitals, schools, hospitality, apartment buildings`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket or tethered cable`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `210 x 290 x 110 mm`,
    weight: `3.2 kg`,
    accessMethod: `RFID card (EO branded RFID tags available)`,
    multiUser: true,
    cableLength: `Socket or tethered (model dependent)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app / fleet billing via EO Cloud`,
    ipRating: `IP55`,
    operatingTemp: `-25°C to +50°C`,
    bidirectional: true,
    bidirectionalNote: `V2G-ready (hardware upgrade available)`,
    warrantyYears: `3 years`,
    notes: `Purpose-built commercial charger. MID-certified energy meter standard. V2G-ready via hardware upgrade — future-proof for vehicle-to-grid use. Pairs with EO Hub 2 for unlimited scalable fleet management.`,
  },
  {
    id: `com-delta-ac-max-commercial-ac-max-smart-7kw`,
    photoUrl: `/images/chargers/delta-ac-max-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Delta AC MAX (Commercial)`,
    variant: `AC MAX Smart 7kW`,
    price: 1400,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, government, apartment buildings, commercial buildings, schools`,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `Taiwan`,
    dimensions: `275 x 390 x 145 mm`,
    weight: `5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Over 3 million EV chargers delivered globally by Delta. Strong local presence via NHP/Delta Australia. Commercial-grade build suited to managed car parks and fleets.`,
  },
  {
    id: `com-delta-ac-max-commercial-ac-max-smart-22kw`,
    photoUrl: `/images/chargers/delta-ac-max-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Delta AC MAX (Commercial)`,
    variant: `AC MAX Smart 22kW`,
    price: 1600,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, fleet, government, apartment buildings, commercial buildings, schools`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 tethered (5m)`,
    countryOfManufacture: `Taiwan`,
    dimensions: `275 x 390 x 145 mm`,
    weight: `5 kg`,
    accessMethod: `RFID card`,
    multiUser: true,
    cableLength: `5m tethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / backend billing`,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Over 3 million EV chargers delivered globally by Delta. Strong local presence via NHP/Delta Australia. Commercial-grade build suited to managed car parks and fleets.`,
  },
  {
    id: `com-fronius-wattpilot-home-22j-commercial-wattpilot-home-11kw`,
    photoUrl: `/images/chargers/fronius-wattpilot-home-commercial-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Fronius Wattpilot Home 22J (Commercial)`,
    variant: `Wattpilot Home 11kW`,
    price: 1249,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, small fleet depots, solar-integrated commercial sites, schools`,
    phase: `Both`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `Austria`,
    dimensions: `148 x 188 x 103 mm`,
    weight: `1.5 kg`,
    accessMethod: `RFID chip/card; up to 10 user profiles`,
    multiUser: true,
    cableLength: `Untethered (cable purchased separately)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP65`,
    operatingTemp: `-20°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `IP65 – best-in-class weatherproofing for an AC wallbox. 10 RFID user profiles make it practical for small commercial/fleet sites. Best value when paired with Fronius solar ecosystem.`,
  },
  {
    id: `com-fronius-wattpilot-home-22j-commercial-wattpilot-home-22kw`,
    photoUrl: `/images/chargers/fronius-wattpilot-home-commercial-2.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Fronius Wattpilot Home 22J (Commercial)`,
    variant: `Wattpilot Home 22kW`,
    price: 1449,
    priceDisplay: null,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Workplaces, small fleet depots, solar-integrated commercial sites, schools`,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `Austria`,
    dimensions: `148 x 188 x 103 mm`,
    weight: `1.5 kg`,
    accessMethod: `RFID chip/card; up to 10 user profiles`,
    multiUser: true,
    cableLength: `Untethered (cable purchased separately)`,
    display: `LED status indicator`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `RFID / app`,
    ipRating: `IP65`,
    operatingTemp: `-20°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `IP65 – best-in-class weatherproofing for an AC wallbox. 10 RFID user profiles make it practical for small commercial/fleet sites. Best value when paired with Fronius solar ecosystem.`,
  },
  {
    id: `com-chargepost-commercial-chargepost-7kw`,
    photoUrl: `/images/chargers/chargepost-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ChargePost Commercial`,
    variant: `ChargePost 7kW`,
    price: null,
    priceDisplay: `POA (contact ChargePost)`,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Councils, kerbside/streetside, public car parks, universities, hospitals, shopping centres`,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `Australia`,
    dimensions: `Pole/bollard integrated unit`,
    weight: `~6 kg`,
    accessMethod: `App, RFID, contactless payment (Tap & Go)`,
    multiUser: true,
    cableLength: `Untethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Contactless Tap & Go, RFID, app`,
    ipRating: `IP65`,
    operatingTemp: `-10°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Australian company specialising in kerbside charging using existing infrastructure (power poles, light columns, bollards). Cost-effective council and streetside solution. Used across NSW/VIC council car parks.`,
  },
  {
    id: `com-chargepost-commercial-chargepost-22kw`,
    photoUrl: `/images/chargers/chargepost-commercial.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `ChargePost Commercial`,
    variant: `ChargePost 22kW`,
    price: null,
    priceDisplay: `POA (contact ChargePost)`,
    chargerType: `AC (Level 2)`,
    suitableApplications: `Councils, kerbside/streetside, public car parks, universities, hospitals, shopping centres`,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `Type 2 socket (untethered)`,
    countryOfManufacture: `Australia`,
    dimensions: `Pole/bollard integrated unit`,
    weight: `~6 kg`,
    accessMethod: `App, RFID, contactless payment (Tap & Go)`,
    multiUser: true,
    cableLength: `Untethered`,
    display: `LED status`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Contactless Tap & Go, RFID, app`,
    ipRating: `IP65`,
    operatingTemp: `-10°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `Australian company specialising in kerbside charging using existing infrastructure (power poles, light columns, bollards). Cost-effective council and streetside solution. Used across NSW/VIC council car parks.`,
  },
  {
    id: `com-delta-dc-fast-charger-australia-dc-25kw-wallbox`,
    photoUrl: `/images/chargers/delta-dc-fast-au.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Delta DC Fast Charger (Australia)`,
    variant: `DC 25kW Wallbox`,
    price: null,
    priceDisplay: `POA (contact Delta/NHP Australia)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Petrol/service stations, retail car parks, fleet depots, government, universities`,
    phase: `Three`,
    power: `25 kW / 50 kW / 100 kW (model dependent)`,
    ratedCurrent: `Up to 250A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `CCS2 + CHAdeMO or CCS2 + CCS2`,
    countryOfManufacture: `Taiwan`,
    dimensions: `Varies by model`,
    weight: `Varies by model`,
    accessMethod: `RFID, Plug & Charge, credit card (model dependent)`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `Touchscreen display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, contactless (model dependent)`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `3 million+ EV chargers delivered globally. Wide DC range from 25kW wallbox to 100kW+ free-standing units. Distributed in Australia by NHP/Delta Australia. Strong after-sales support.`,
  },
  {
    id: `com-delta-dc-fast-charger-australia-dc-50kw`,
    photoUrl: `/images/chargers/delta-dc-fast-au.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Delta DC Fast Charger (Australia)`,
    variant: `DC 50kW`,
    price: null,
    priceDisplay: `POA (contact Delta/NHP Australia)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Petrol/service stations, retail car parks, fleet depots, government, universities`,
    phase: `Three`,
    power: `25 kW / 50 kW / 100 kW (model dependent)`,
    ratedCurrent: `Up to 250A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `CCS2 + CHAdeMO or CCS2 + CCS2`,
    countryOfManufacture: `Taiwan`,
    dimensions: `Varies by model`,
    weight: `Varies by model`,
    accessMethod: `RFID, Plug & Charge, credit card (model dependent)`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `Touchscreen display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, contactless (model dependent)`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `3 million+ EV chargers delivered globally. Wide DC range from 25kW wallbox to 100kW+ free-standing units. Distributed in Australia by NHP/Delta Australia. Strong after-sales support.`,
  },
  {
    id: `com-delta-dc-fast-charger-australia-dc-100kw`,
    photoUrl: `/images/chargers/delta-dc-fast-au.png`,
    photoFit: `contain`,
    category: `Commercial`,
    brand: `Delta DC Fast Charger (Australia)`,
    variant: `DC 100kW`,
    price: null,
    priceDisplay: `POA (contact Delta/NHP Australia)`,
    chargerType: `DC Fast Charger`,
    suitableApplications: `Petrol/service stations, retail car parks, fleet depots, government, universities`,
    phase: `Three`,
    power: `25 kW / 50 kW / 100 kW (model dependent)`,
    ratedCurrent: `Up to 250A`,
    numberOfPorts: `1 or 2 (model dependent)`,
    connectorType: `CCS2 + CHAdeMO or CCS2 + CCS2`,
    countryOfManufacture: `Taiwan`,
    dimensions: `Varies by model`,
    weight: `Varies by model`,
    accessMethod: `RFID, Plug & Charge, credit card (model dependent)`,
    multiUser: true,
    cableLength: `Tethered cables`,
    display: `Touchscreen display`,
    loadManagement: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    paymentOptions: `Credit card, RFID, contactless (model dependent)`,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    notes: `3 million+ EV chargers delivered globally. Wide DC range from 25kW wallbox to 100kW+ free-standing units. Distributed in Australia by NHP/Delta Australia. Strong after-sales support.`,
  },
];
