// Auto-generated from Comparison-Residential_EV_Chargers_updated.xlsx — do not hand-edit structure, regenerate instead.
import type { ResidentialCharger } from "./charger-types";

export const residentialChargers: ResidentialCharger[] = [
  {
    id: `res-myenergi-zappi-zappi-single-phase`,
    photoUrl: `/images/chargers/zappi.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Myenergi Zappi`,
    variant: `Zappi single-phase`,
    price: 1595,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A max`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `439 x 282 x 122mm`,
    weight: `5.5 kg`,
    cableLength: `6.5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `3 mode - Eco, Eco+, Fast`,
  },
  {
    id: `res-myenergi-zappi-zappi-three-phase`,
    photoUrl: `/images/chargers/zappi.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Myenergi Zappi`,
    variant: `Zappi three-phase`,
    price: 1895,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A max`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `439 x 282 x 122mm`,
    weight: `5.5 kg`,
    cableLength: `6.5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25°C to +40°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `3 mode - Eco, Eco+, Fast`,
  },
  {
    id: `res-sigenergy-ac-ev-charger-sigen-evac-7`,
    photoUrl: `/images/chargers/sigenergy-ac.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sigenergy AC EV Charger`,
    variant: `Sigen EVAC 7`,
    price: 1200,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `234 x 384 x 126`,
    weight: `6.4 kg`,
    cableLength: `5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30 - +55 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `100% PV charging / Solar boost charging / Fast charging`,
  },
  {
    id: `res-sigenergy-ac-ev-charger-sigen-evac-11`,
    photoUrl: `/images/chargers/sigenergy-ac.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sigenergy AC EV Charger`,
    variant: `Sigen EVAC 11`,
    price: 1300,
    priceDisplay: null,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    countryOfManufacture: `China`,
    dimensions: `234 x 384 x 126`,
    weight: `6.4 kg`,
    cableLength: `5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30 - +55 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `100% PV charging / Solar boost charging / Fast charging`,
  },
  {
    id: `res-sigenergy-ac-ev-charger-sigen-evac-22`,
    photoUrl: `/images/chargers/sigenergy-ac.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sigenergy AC EV Charger`,
    variant: `Sigen EVAC 22`,
    price: 1500,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `234 x 384 x 126`,
    weight: `6.4 kg`,
    cableLength: `5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30 - +55 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `100% PV charging / Solar boost charging / Fast charging`,
  },
  {
    id: `res-sigenstor-ev-dc-sigenstor-evdc-12-5`,
    photoUrl: `/images/chargers/sigenstor-dc.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sigenstor EV DC`,
    variant: `SigenStor EVDC 12.5`,
    price: 6700,
    priceDisplay: null,
    phase: `Both`,
    power: `12.5 kW`,
    ratedCurrent: `40A`,
    countryOfManufacture: `China`,
    dimensions: `700 x 270 x 260`,
    weight: `40 kg`,
    cableLength: `5 / 7.5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP66`,
    operatingTemp: `-30 - +60 °C`,
    bidirectional: true,
    warrantyYears: `3 years`,
    chargingModes: `Fast, eco`,
    notes: `Module of the Sigenstor all-in-one battery. Must be paired with the Sigen Energy Controller (inverter).`,
  },
  {
    id: `res-sigenstor-ev-dc-sigenstor-evdc-25`,
    photoUrl: `/images/chargers/sigenstor-dc.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sigenstor EV DC`,
    variant: `SigenStor EVDC 25`,
    price: 8600,
    priceDisplay: null,
    phase: `Both`,
    power: `25 kW`,
    ratedCurrent: `80A`,
    countryOfManufacture: `China`,
    dimensions: `700 x 270 x 260`,
    weight: `40 kg`,
    cableLength: `5 / 7.5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP66`,
    operatingTemp: `-30 - +60 °C`,
    bidirectional: true,
    warrantyYears: `3 years`,
    chargingModes: `Fast, eco`,
    notes: `Module of the Sigenstor all-in-one battery. Must be paired with the Sigen Energy Controller (inverter).`,
  },
  {
    id: `res-ocular-iq-solar-iocah10r-7s-iocah10r-7t`,
    photoUrl: `/images/chargers/ocular-iq-solar.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular IQ Solar`,
    variant: `IOCAH10R-7S / IOCAH10R-7T`,
    price: 1400,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `269 x 360 x 146 mm`,
    weight: `7.6 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-ocular-iq-solar-iocah10r-22s-iocah10r-22t`,
    photoUrl: `/images/chargers/ocular-iq-solar.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular IQ Solar`,
    variant: `IOCAH10R-22S / IOCAH10R-22T`,
    price: 1550,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `269 x 360 x 146 mm`,
    weight: `7.6 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-ocular-lte-oc20-bc-7-2kw`,
    photoUrl: `/images/chargers/ocular-lte.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular LTE`,
    variant: `OC20-BC-7.2KW`,
    price: 899,
    priceDisplay: null,
    phase: `Single`,
    power: `7.6 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `295 x 195 x 65 mm`,
    weight: `8 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: false,
    internetConnection: false,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP66`,
    operatingTemp: `-30 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-ocular-lte-oc20-bc-22kw`,
    photoUrl: `/images/chargers/ocular-lte.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular LTE`,
    variant: `OC20-BC-22KW`,
    price: 1200,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `295 x 195 x 65 mm`,
    weight: `8 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: false,
    internetConnection: false,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP66`,
    operatingTemp: `-30 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-tesla-gen-3-wall-connector-gen-3-wall-connector`,
    photoUrl: `/images/chargers/tesla-gen3.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Tesla Gen 3 Wall Connector`,
    variant: `Gen 3 Wall Connector`,
    price: 800,
    priceDisplay: null,
    phase: `Both`,
    power: `7 kW (1 ph),
22 kW (3 ph)`,
    ratedCurrent: `32A per phase`,
    countryOfManufacture: `China`,
    dimensions: `345 x 155 x 110 mm`,
    weight: `6.8 kg`,
    cableLength: `7.3 meters`,
    display: `No`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30 °C to 50 °C`,
    bidirectional: false,
    warrantyYears: `4 years`,
    chargingModes: `Fast, scheduled`,
  },
  {
    id: `res-ev-switch-evs-ac-070h-01`,
    photoUrl: `/images/chargers/ev-switch.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EV Switch`,
    variant: `EVS-AC-070H-01`,
    price: 699,
    priceDisplay: null,
    phase: `Single`,
    power: `7kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `344 x 192 x 100 mm`,
    weight: `2.4 kg`,
    cableLength: `7 meters`,
    display: `LED`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30 to +50°C`,
    bidirectional: false,
    warrantyYears: `1 year`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-goodwe-hca-series-gw7k-hca`,
    photoUrl: `/images/chargers/goodwe-hca.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `GoodWe HCA Series`,
    variant: `GW7K-HCA`,
    price: 850,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `208 × 450 × 150`,
    weight: `6 kg`,
    cableLength: `6 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP66`,
    operatingTemp: `-30 ~ +50 C`,
    bidirectional: false,
    warrantyYears: `2`,
    chargingModes: `Fast charge, charging from PV only and charging from PV & Battery only.`,
  },
  {
    id: `res-goodwe-hca-series-gw11k-hca`,
    photoUrl: `/images/chargers/goodwe-hca.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `GoodWe HCA Series`,
    variant: `GW11K-HCA`,
    price: 950,
    priceDisplay: null,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16 A`,
    countryOfManufacture: `China`,
    dimensions: `208 × 450 × 150`,
    weight: `6 kg`,
    cableLength: `6 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP66`,
    operatingTemp: `-30 ~ +50 C`,
    bidirectional: false,
    warrantyYears: `2`,
    chargingModes: `Fast charge, charging from PV only and charging from PV & Battery only.`,
  },
  {
    id: `res-goodwe-hca-series-gw22k-hca`,
    photoUrl: `/images/chargers/goodwe-hca.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `GoodWe HCA Series`,
    variant: `GW22K-HCA`,
    price: 1100,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `China`,
    dimensions: `208 × 450 × 150`,
    weight: `6 kg`,
    cableLength: `6 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP66`,
    operatingTemp: `-30 ~ +50 C`,
    bidirectional: false,
    warrantyYears: `2`,
    chargingModes: `Fast charge, charging from PV only and charging from PV & Battery only.`,
  },
  {
    id: `res-sungrow-ac22e-01-ac22e-01`,
    photoUrl: `/images/chargers/sungrow-ac22e.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Sungrow AC22E-01`,
    variant: `AC22E-01`,
    price: 950,
    priceDisplay: null,
    phase: `Both`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `214 x 346 x 125 mm`,
    weight: `6.6 kg`,
    cableLength: `5m / 7m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30 ℃ - 50 ℃`,
    bidirectional: false,
    warrantyYears: `3`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-wallbox-pulsar-max-pulsar-max-single-phase`,
    photoUrl: `/images/chargers/wallbox-pulsar-max.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Wallbox Pulsar Max`,
    variant: `Pulsar Max single phase`,
    price: 1400,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Spain`,
    dimensions: `204 x 313 x 142 mm`,
    weight: `2.5 kg`,
    cableLength: `5m / 7m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Power boost, Eco-smart, Eco-mode`,
  },
  {
    id: `res-wallbox-pulsar-max-pulsar-plus-three-phase`,
    photoUrl: `/images/chargers/wallbox-pulsar-max.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Wallbox Pulsar Max`,
    variant: `Pulsar Plus three phase`,
    price: 1650,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Spain`,
    dimensions: `204 x 313 x 142 mm`,
    weight: `2.5 kg`,
    cableLength: `5m / 7m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Power boost, Eco-smart, Eco-mode`,
  },
  {
    id: `res-wallbox-pulsar-plus-pulsar-plus-single-phase`,
    photoUrl: `/images/chargers/wallbox-pulsar-plus.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Wallbox Pulsar Plus`,
    variant: `Pulsar Plus single phase`,
    price: 1549,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Spain`,
    dimensions: `166 x 163 x 82 mm`,
    weight: `2 kg`,
    cableLength: `5m / 7m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Power boost, Eco-smart, Eco-mode`,
  },
  {
    id: `res-wallbox-pulsar-plus-pulsar-plus-three-phase`,
    photoUrl: `/images/chargers/wallbox-pulsar-plus.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Wallbox Pulsar Plus`,
    variant: `Pulsar Plus three phase`,
    price: 1649,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Spain`,
    dimensions: `166 x 163 x 82 mm`,
    weight: `2 kg`,
    cableLength: `5m / 7m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Power boost, Eco-smart, Eco-mode`,
  },
  {
    id: `res-solaredge-one-ev-charger-evn22b`,
    photoUrl: `/images/chargers/solaredge-one.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `SolarEdge ONE EV Charger`,
    variant: `EVN22B`,
    price: 1200,
    priceDisplay: null,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `235 x 230 x 130 mm`,
    weight: `1.8 kg`,
    cableLength: `N/A`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30~50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Smart schedules, excess solar charging`,
  },
  {
    id: `res-solaredge-one-ev-charger-evn22p`,
    photoUrl: `/images/chargers/solaredge-one.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `SolarEdge ONE EV Charger`,
    variant: `EVN22P`,
    price: 1750,
    priceDisplay: null,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `235 x 230 x 130 mm`,
    weight: `1.8 kg`,
    cableLength: `N/A`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30~50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Smart schedules, excess solar charging`,
  },
  {
    id: `res-fronius-wattpilot-wattpilot-home-22-j`,
    photoUrl: `/images/chargers/fronius-wattpilot-2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Fronius Wattpilot`,
    variant: `WATTPILOT HOME 22 J`,
    price: 1800,
    priceDisplay: null,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `6-32 A`,
    countryOfManufacture: `Austria`,
    dimensions: `155 x 110 x 260 mm`,
    weight: `2 kg`,
    cableLength: `N/A`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP55`,
    operatingTemp: `-25 ºC to +40 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Eco Mode, Next-Trip Mode (both use Solar Surplus), Time Scheduler`,
  },
  {
    id: `res-fronius-wattpilot-flex-home-wattpilot-flex-home-22-c6`,
    photoUrl: `/images/chargers/fronius-wattpilot-flex-home.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Fronius Wattpilot Flex Home`,
    variant: `Wattpilot Flex Home 22 C6`,
    price: 1900,
    priceDisplay: null,
    phase: `Both`,
    power: `22 kW`,
    ratedCurrent: `6-32 A`,
    countryOfManufacture: `Austria`,
    dimensions: `325 x 195 x 105 mm`,
    weight: `5.4 kg`,
    cableLength: `6m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: false,
    ipRating: `IP66`,
    operatingTemp: `-25 ºC to +45 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Eco Mode, Next-Trip Mode (both use Solar Surplus), Time Scheduler`,
  },
  {
    id: `res-schneider-charge-schneider-charge`,
    photoUrl: `/images/chargers/schneider-charge.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Schneider Charge`,
    variant: `Schneider Charge`,
    price: 1500,
    priceDisplay: null,
    phase: `Both`,
    power: `7-22 kW`,
    ratedCurrent: `16-32 A`,
    countryOfManufacture: `China`,
    dimensions: `352 x 244 x 117 mm`,
    weight: `3.2 kg`,
    cableLength: `5m / 7m`,
    display: `Yes (LEDs)`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP55`,
    operatingTemp: `-30 ºC to 50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Custom schedule, "Reduce my bill" mode, dynamic load balancing`,
  },
  {
    id: `res-solax-g2-x1-hac-7`,
    photoUrl: `/images/chargers/solax-g2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `SolaX G2`,
    variant: `X1-HAC-7`,
    price: 750,
    priceDisplay: null,
    phase: `Single`,
    power: `7.2kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `206 × 390 × 139 mm`,
    weight: `6.5 kg`,
    cableLength: `6.5m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25 to 50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-solax-g2-x3-hac-22`,
    photoUrl: `/images/chargers/solax-g2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `SolaX G2`,
    variant: `X3-HAC-22`,
    price: 900,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `206 × 390 × 139 mm`,
    weight: `6.5 kg`,
    cableLength: `6.5m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25 to 50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-delta-ac-max-smart-ac-max-single-phase`,
    photoUrl: `/images/chargers/delta-ac-max-smart.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Delta AC MAX (smart)`,
    variant: `AC MAX Single Phase`,
    price: 1990,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Unknown - manufacturer unresponsive`,
    dimensions: `218 x 371 x 167 mm`,
    weight: `3.8 kg`,
    cableLength: `5 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30 ºC to +50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-delta-ac-max-smart-ac-max-three-phase`,
    photoUrl: `/images/chargers/delta-ac-max-smart.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Delta AC MAX (smart)`,
    variant: `AC MAX Three Phase`,
    price: 2290,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Unknown - manufacturer unresponsive`,
    dimensions: `218 x 371 x 167 mm`,
    weight: `3.8 kg`,
    cableLength: `5 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30 ºC to +50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-delta-ac-max-basic-ac-max-single-phase`,
    photoUrl: `/images/chargers/delta-ac-max-basic.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Delta AC MAX (basic)`,
    variant: `AC MAX Single Phase`,
    price: 1590,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Unknown - manufacturer unresponsive`,
    dimensions: `218 x 371 x 167 mm`,
    weight: `3.8 kg`,
    cableLength: `5 meters`,
    display: `No`,
    solarSmart: false,
    internetConnection: false,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30 ºC to +50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-delta-ac-max-basic-ac-max-three-phase`,
    photoUrl: `/images/chargers/delta-ac-max-basic.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Delta AC MAX (basic)`,
    variant: `AC MAX Three Phase`,
    price: 1890,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Unknown - manufacturer unresponsive`,
    dimensions: `218 x 371 x 167 mm`,
    weight: `3.8 kg`,
    cableLength: `5 meters`,
    display: `No`,
    solarSmart: false,
    internetConnection: false,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30 ºC to +50 ºC`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-victron-ev-charging-station-ev-charging-station`,
    photoUrl: `/images/chargers/victron.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Victron EV Charging Station`,
    variant: `EV Charging Station`,
    price: 1000,
    priceDisplay: null,
    phase: `Both`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Netherlands`,
    dimensions: `390 x 300 x 150 mm`,
    weight: `3 kg`,
    cableLength: `N/A`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP44`,
    operatingTemp: `-25 - +50 °C`,
    bidirectional: false,
    warrantyYears: `5 years`,
    chargingModes: `Manual mode/Automatic mode`,
  },
  {
    id: `res-zj-beny-ac-ev-charger-ac-ev-charger-single-phase`,
    photoUrl: `/images/chargers/zj-beny.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `ZJ Beny AC EV Charger`,
    variant: `AC EV Charger - Single Phase`,
    price: 750,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `169 x 380 x 151 mm`,
    weight: `9 kg`,
    cableLength: `6 meters`,
    display: `Yes - charging indicator`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-25°C - +55°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Multiple - see datasheet`,
    notes: `Available both tethered and untethered`,
  },
  {
    id: `res-zj-beny-ac-ev-charger-ac-ev-charger-three-phase`,
    photoUrl: `/images/chargers/zj-beny.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `ZJ Beny AC EV Charger`,
    variant: `AC EV Charger - Three Phase`,
    price: 1000,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `169 x 380 x 151 mm`,
    weight: `9 kg`,
    cableLength: `6 meters`,
    display: `Yes - charging indicator`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-25°C - +55°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Multiple - see datasheet`,
    notes: `Available both tethered and untethered`,
  },
  {
    id: `res-evnex-e2-e2-25sn`,
    photoUrl: `/images/chargers/evnex-e2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Evnex E2`,
    variant: `E2-25SN`,
    price: 1395,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `New Zealand`,
    dimensions: `286 x 185 x 66 mm`,
    weight: `2.3 kg`,
    cableLength: `5 meter, 8 meter`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: true,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-25°C to 55°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, Solar with Grid Fallback, Fast and Dynamic Load Balancing`,
    notes: `Free Evnex Residential App, Carbon Tracking, Electricity Tariff Setting, Charging Session History, and Charging Schedule.`,
  },
  {
    id: `res-smappee-ev-wall-ev-wall-single-phase`,
    photoUrl: `/images/chargers/smappee-ev-wall.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Smappee EV Wall`,
    variant: `EV Wall single-phase`,
    price: 1729,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Belgium`,
    dimensions: `300 × 300 × 110 mm`,
    weight: `9.8 kg`,
    cableLength: `8 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 °C to 40 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, scheduled, fast`,
  },
  {
    id: `res-smappee-ev-wall-ev-wall-three-phase`,
    photoUrl: `/images/chargers/smappee-ev-wall.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Smappee EV Wall`,
    variant: `EV Wall three-phase`,
    price: 2229,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `Belgium`,
    dimensions: `300 × 300 × 110 mm`,
    weight: `9.8 kg`,
    cableLength: `8 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25 °C to 40 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, scheduled, fast`,
  },
  {
    id: `res-ohme-home-pro-hp5-07au-wi-blstd-01`,
    photoUrl: `/images/chargers/ohme-home-pro.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ohme Home Pro`,
    variant: `HP5-07AU-WI-BLSTD-01`,
    price: 1395,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `200 x 170 x 100 mm`,
    weight: `4 kg`,
    cableLength: `5m / 8m`,
    display: `Yes - LCD Screen and LED charging status bar`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-25°C to 45°C`,
    bidirectional: false,
    warrantyYears: `3 years from installation date`,
    chargingModes: `Dynamic Load Balancing & Solar Compatible`,
  },
  {
    id: `res-ohme-epod-ep0-07au-wi-blstd-01`,
    photoUrl: `/images/chargers/ohme-epod.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ohme ePod`,
    variant: `EP0-07AU-WI-BLSTD-01`,
    price: 1199,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `230mm x 150mm x 140mm`,
    weight: `1.5 kg`,
    cableLength: `Untethered`,
    display: `Yes – LED charging status bar`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-25°C to 50°C`,
    bidirectional: false,
    warrantyYears: `3 years from installation date`,
    chargingModes: `Dynamic Load Balancing & Solar Compatible`,
  },
  {
    id: `res-abb-terra-wallbox-terra-ac-w7`,
    photoUrl: `/images/chargers/abb-terra-wallbox-2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `ABB Terra Wallbox`,
    variant: `Terra AC W7`,
    price: 2000,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Italy`,
    dimensions: `320 x 195 x 110 mm`,
    weight: `6.5 kg`,
    cableLength: `5m or 7.6m`,
    display: `Yes`,
    solarSmart: false,
    solarSmartNote: `With additional hardware`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-35 - +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-abb-terra-wallbox-terra-ac-w11`,
    photoUrl: `/images/chargers/abb-terra-wallbox-2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `ABB Terra Wallbox`,
    variant: `Terra AC W11`,
    price: 2300,
    priceDisplay: null,
    phase: `Three`,
    power: `11 kW`,
    ratedCurrent: `16A`,
    countryOfManufacture: `Italy`,
    dimensions: `320 x 195 x 110 mm`,
    weight: `6.5 kg`,
    cableLength: `5m or 7.6m`,
    display: `Yes`,
    solarSmart: false,
    solarSmartNote: `With additional hardware`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-35 - +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-abb-terra-wallbox-terra-ac-w22`,
    photoUrl: `/images/chargers/abb-terra-wallbox-2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `ABB Terra Wallbox`,
    variant: `Terra AC W22`,
    price: 2400,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Italy`,
    dimensions: `320 x 195 x 110 mm`,
    weight: `6.5 kg`,
    cableLength: `5m or 7.6m`,
    display: `Yes`,
    solarSmart: false,
    solarSmartNote: `With additional hardware`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-35 - +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Unknown - manufacturer unresponsive`,
  },
  {
    id: `res-enphase-iq-ev-charger-2-iq-evse-eu-3032-0105-1300`,
    photoUrl: `/images/chargers/enphase-iq2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Enphase IQ EV Charger 2`,
    variant: `IQ-EVSE-EU-3032-0105-1300`,
    price: 2048,
    priceDisplay: null,
    phase: `Both`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `TBD`,
    dimensions: `370 × 250 × 118 mm`,
    weight: `11 kg`,
    cableLength: `7.5 m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-40°C to 55°C`,
    bidirectional: true,
    bidirectionalNote: `V2X "capable" with software unlock`,
    warrantyYears: `5`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-istore-ev-charger-is-evc-7400-1ph`,
    photoUrl: `/images/chargers/istore.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `iStore EV Charger`,
    variant: `IS-EVC-7400-1PH`,
    price: 1200,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `380 x 169 x 151 mm`,
    weight: `7 kg`,
    cableLength: `7 meters`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-25°C ~ 55°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Standard, solar-only`,
  },
  {
    id: `res-istore-ev-charger-is-evc-22000-3ph`,
    photoUrl: `/images/chargers/istore.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `iStore EV Charger`,
    variant: `IS-EVC-22000-3PH`,
    price: 1500,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `380 x 169 x 151 mm`,
    weight: `7 kg`,
    cableLength: `7 meters`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-25°C ~ 55°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Standard, solar-only`,
  },
  {
    id: `res-anker-solix-v1-smart-ev-charger-v1-7-4`,
    photoUrl: `/images/chargers/anker-solix-v1.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Anker Solix V1 Smart EV Charger`,
    variant: `V1-7.4`,
    price: 800,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `211 x 360 x 120 mm`,
    weight: `4.95 kg`,
    cableLength: `7 meters`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30°C to 50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast, solar-only`,
  },
  {
    id: `res-anker-solix-v1-smart-ev-charger-v1-22`,
    photoUrl: `/images/chargers/anker-solix-v1.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Anker Solix V1 Smart EV Charger`,
    variant: `V1-22`,
    price: 1000,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `211 x 360 x 120 mm`,
    weight: `4.95 kg`,
    cableLength: `7 meters`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-30°C to 50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast, solar-only`,
  },
  {
    id: `res-teltonika-teltocharge-evc-100`,
    photoUrl: `/images/chargers/teltonika-teltocharge.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Teltonika TeltoCharge`,
    variant: `EVC 100`,
    price: 1450,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Lithuania`,
    dimensions: `170 mm x 341 mm x 94 mm`,
    weight: `2.8 kg`,
    cableLength: `5m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30ºC - +50ºC`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar/Dynamic load balancing`,
  },
  {
    id: `res-teltonika-teltocharge-evc-110`,
    photoUrl: `/images/chargers/teltonika-teltocharge.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Teltonika TeltoCharge`,
    variant: `EVC 110`,
    price: 1750,
    priceDisplay: null,
    phase: `Three`,
    power: `11kW`,
    ratedCurrent: `16A`,
    countryOfManufacture: `Lithuania`,
    dimensions: `170 mm x 341 mm x 94 mm`,
    weight: `2.8 kg`,
    cableLength: `5m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30ºC - +50ºC`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar/Dynamic load balancing`,
  },
  {
    id: `res-teltonika-teltocharge-evc-120`,
    photoUrl: `/images/chargers/teltonika-teltocharge.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Teltonika TeltoCharge`,
    variant: `EVC 120`,
    price: 2000,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Lithuania`,
    dimensions: `170 mm x 341 mm x 94 mm`,
    weight: `2.8 kg`,
    cableLength: `5m`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30ºC - +50ºC`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar/Dynamic load balancing`,
  },
  {
    id: `res-eo-mini-pro-2-mini-pro-2`,
    photoUrl: `/images/chargers/eo-mini-pro-2.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EO Mini Pro 2`,
    variant: `Mini Pro 2`,
    price: 1495,
    priceDisplay: null,
    phase: `Single`,
    power: `7.2 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `175mm x 125mm x 125mm`,
    weight: `1.3 kg`,
    cableLength: `5 meters`,
    display: `No`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-10 °C to 50 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar-only, fast`,
  },
  {
    id: `res-eo-basic-basic-single-phase`,
    photoUrl: `/images/chargers/eo-basic.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EO Basic`,
    variant: `Basic single-phase`,
    price: 1400,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `360mm x 165mm x 155mm`,
    weight: `1.3 kg`,
    cableLength: `N/A`,
    display: `No`,
    solarSmart: false,
    internetConnection: true,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-10 °C to 50 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast`,
  },
  {
    id: `res-eo-basic-basic-three-phase`,
    photoUrl: `/images/chargers/eo-basic.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EO Basic`,
    variant: `Basic three-phase`,
    price: 1600,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32 A`,
    countryOfManufacture: `United Kingdom`,
    dimensions: `360mm x 165mm x 155mm`,
    weight: `1.3 kg`,
    cableLength: `N/A`,
    display: `No`,
    solarSmart: false,
    internetConnection: true,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-10 °C to 50 °C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast`,
  },
  {
    id: `res-fox-ess-a-series-a07kp1-e-b`,
    photoUrl: `/images/chargers/fox-ess-a-series.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Fox ESS A-Series`,
    variant: `A07KP1-E-B`,
    price: 799,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `320 x 190 x 145mm`,
    weight: `5.4 kg`,
    cableLength: `6m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-30 to +50C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar only, solar surplus, smart schedules`,
    notes: `Free FoxCloud2.0 app controls entire Fox ESS ecosystem (inverter, battery, EV charger); Fox Switch App (simple & dedicated EV Charging app for EV charger only users)`,
  },
  {
    id: `res-fox-ess-a-series-a022kp1-e-b`,
    photoUrl: `/images/chargers/fox-ess-a-series.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Fox ESS A-Series`,
    variant: `A022KP1-E-B`,
    price: 1099,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `320 x 190 x 145mm`,
    weight: `5.4 kg`,
    cableLength: `6m`,
    display: `LED`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-30 to +50C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Solar only, solar surplus, smart schedules`,
    notes: `Free FoxCloud2.0 app controls entire Fox ESS ecosystem (inverter, battery, EV charger); Fox Switch App (simple & dedicated EV Charging app for EV charger only users)`,
  },
  {
    id: `res-evos-fleet22-fleet22`,
    photoUrl: `/images/chargers/evos-fleet22.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EVOS Fleet22`,
    variant: `Fleet22`,
    price: 1800,
    priceDisplay: null,
    phase: `Both`,
    power: `7-22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Australia`,
    dimensions: `380 x 100mm`,
    weight: `6.5 kg`,
    cableLength: `5 or 6 meters`,
    display: `LED colour status`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: true,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-25 °C to 55 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar only, Dynamic Load Balancing, Time Schedule, Tariff Schedule, Load Balancing.`,
    notes: `Free "MyEVOS" app for stop/start/restart, tariff selection and historical charging data`,
  },
  {
    id: `res-evos-sb7-sb7`,
    photoUrl: `/images/chargers/evos-sb7.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `EVOS SB7`,
    variant: `SB7`,
    price: 1400,
    priceDisplay: null,
    phase: `Single`,
    power: `7.36 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Australia`,
    dimensions: `320 x 90mm`,
    weight: `3.5 kg`,
    cableLength: `5m`,
    display: `LED colour status`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: true,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-25 °C to 55 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar only, Dynamic Load Balancing, Time Schedule, Tariff Schedule, Load Balancing.`,
    notes: `Free "MyEVOS" app for stop/start/restart, tariff selection and historical charging data`,
  },
  {
    id: `res-weidmuller-ac-smart-ch-w-s-a7-4-p-e`,
    photoUrl: `/images/chargers/weidmuller-ac-smart.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Weidmuller AC SMART`,
    variant: `CH-W-S-A7.4-P-E`,
    price: 800,
    priceDisplay: null,
    phase: `Single`,
    power: `7kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Germany`,
    dimensions: `268 x 433 x 150 mm`,
    weight: `5.1 kg`,
    cableLength: `5m, 7m, 10m`,
    display: `No`,
    solarSmart: false,
    solarSmartNote: `On "Value" and "Advanced" models`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-30 °C to +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar, fast`,
  },
  {
    id: `res-weidmuller-ac-smart-ch-w-s-a11-p`,
    photoUrl: `/images/chargers/weidmuller-ac-smart.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Weidmuller AC SMART`,
    variant: `CH-W-S-A11-P`,
    price: 1600,
    priceDisplay: null,
    phase: `Three`,
    power: `11kW`,
    ratedCurrent: `16A`,
    countryOfManufacture: `Germany`,
    dimensions: `268 x 433 x 150 mm`,
    weight: `5.1 kg`,
    cableLength: `5m, 7m, 10m`,
    display: `No`,
    solarSmart: false,
    solarSmartNote: `On "Value" and "Advanced" models`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-30 °C to +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar, fast`,
  },
  {
    id: `res-weidmuller-ac-smart-ch-w-s-a22-p`,
    photoUrl: `/images/chargers/weidmuller-ac-smart.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Weidmuller AC SMART`,
    variant: `CH-W-S-A22-P`,
    price: 1800,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Germany`,
    dimensions: `268 x 433 x 150 mm`,
    weight: `5.1 kg`,
    cableLength: `5m, 7m, 10m`,
    display: `No`,
    solarSmart: false,
    solarSmartNote: `On "Value" and "Advanced" models`,
    internetConnection: true,
    appControl: true,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP54`,
    operatingTemp: `-30 °C to +50 °C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar, fast`,
  },
  {
    id: `res-soltaro-ev-charger-7kw`,
    photoUrl: `/images/chargers/soltaro.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Soltaro EV Charger`,
    variant: `7kW`,
    price: 1050,
    priceDisplay: null,
    phase: `Single`,
    power: `7kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `368 x 168 x 215 mm`,
    weight: `8 kg`,
    cableLength: `6m default`,
    display: `LEDs`,
    solarSmart: true,
    internetConnection: true,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25-55 C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Full Speed, Solar Optimised, Hybrid`,
  },
  {
    id: `res-soltaro-ev-charger-22kw`,
    photoUrl: `/images/chargers/soltaro.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Soltaro EV Charger`,
    variant: `22kW`,
    price: 1450,
    priceDisplay: null,
    phase: `Three`,
    power: `22kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `368 x 168 x 215 mm`,
    weight: `8 kg`,
    cableLength: `6m default`,
    display: `LEDs`,
    solarSmart: true,
    internetConnection: true,
    appControl: false,
    ocppCompatible: false,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP65`,
    operatingTemp: `-25-55 C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Full Speed, Solar Optimised, Hybrid`,
  },
  {
    id: `res-scame-be-w-net-be-w-net-single-phase`,
    photoUrl: `/images/chargers/scame-be-w-net.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Scame BE-W Net`,
    variant: `BE-W Net Single Phase`,
    price: 1800,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Italy`,
    dimensions: `235 x 370 x 115 mm`,
    weight: `6.2 kg`,
    cableLength: `4m`,
    display: `Yes`,
    solarSmart: false,
    internetConnection: true,
    appControl: false,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `4 years`,
    chargingModes: `Ecoplus, Ecosmart, Full`,
  },
  {
    id: `res-scame-be-w-net-be-w-net-three-phase`,
    photoUrl: `/images/chargers/scame-be-w-net.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Scame BE-W Net`,
    variant: `BE-W Net Three Phase`,
    price: 2100,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `Italy`,
    dimensions: `235 x 370 x 115 mm`,
    weight: `6.2 kg`,
    cableLength: `4m`,
    display: `Yes`,
    solarSmart: false,
    internetConnection: true,
    appControl: false,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP54`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `4 years`,
    chargingModes: `Ecoplus, Ecosmart, Full`,
  },
  {
    id: `res-starcharge-halo-ad20074eu1923`,
    photoUrl: `/images/chargers/starcharge-halo.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `StarCharge Halo`,
    variant: `AD20074EU1923`,
    price: 5990,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `323 × 480 × 175 mm`,
    weight: `23 kg`,
    cableLength: `5m`,
    display: `LED`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP65`,
    operatingTemp: `-30 to 50℃`,
    bidirectional: true,
    warrantyYears: `2 years`,
    chargingModes: `Standard, bi-directional`,
  },
  {
    id: `res-autel-maxicharger-ac-lite-ac-lite-single-phase`,
    photoUrl: `/images/chargers/autel-ac-lite.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Autel MaxiCharger AC Lite`,
    variant: `AC Lite Single Phase`,
    price: 770,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `235 x 190 x 56 mm`,
    weight: `1.5 kg`,
    cableLength: `5 meters`,
    display: `LED`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: false,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `4 years`,
    chargingModes: `Fast`,
    notes: `Entry-level charger distributed and supported locally by JET Charge Australia. Competitive 4-year warranty.`,
  },
  {
    id: `res-autel-maxicharger-ac-wallbox-ac-wallbox-single-phase`,
    photoUrl: `/images/chargers/autel-ac-wallbox.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Autel MaxiCharger AC Wallbox`,
    variant: `AC Wallbox Single Phase`,
    price: 968,
    priceDisplay: null,
    phase: `Single`,
    power: `7.4 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `235 x 190 x 56 mm`,
    weight: `1.8 kg`,
    cableLength: `5 meters`,
    display: `LED`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast, scheduled`,
    notes: `Mid-range model with Wi-Fi & Bluetooth. Distributed and supported locally by JET Charge Australia.`,
  },
  {
    id: `res-autel-maxicharger-ac-wallbox-ac-wallbox-three-phase`,
    photoUrl: `/images/chargers/autel-ac-wallbox.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Autel MaxiCharger AC Wallbox`,
    variant: `AC Wallbox Three Phase`,
    price: 1479,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `235 x 190 x 56 mm`,
    weight: `1.8 kg`,
    cableLength: `5 meters`,
    display: `LED`,
    solarSmart: false,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `3 years`,
    chargingModes: `Fast, scheduled`,
    notes: `Mid-range model with Wi-Fi & Bluetooth. Distributed and supported locally by JET Charge Australia.`,
  },
  {
    id: `res-ocular-iq-home-solar-iocah10r-7s`,
    photoUrl: `/images/chargers/ocular-iq-home-solar.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular IQ Home Solar`,
    variant: `IOCAH10R-7S`,
    price: 1400,
    priceDisplay: null,
    phase: `Single`,
    power: `7 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `269 x 360 x 146 mm`,
    weight: `7.6 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar-only, Solar Assist, Fast`,
    notes: `Includes CT clamps for measuring solar excess. All-in-one solar, load management and app control. Distributed by EVSE Australia, established since 2016.`,
  },
  {
    id: `res-ocular-iq-home-solar-iocah10r-22t`,
    photoUrl: `/images/chargers/ocular-iq-home-solar.png`,
    photoFit: `contain`,
    category: `Residential`,
    brand: `Ocular IQ Home Solar`,
    variant: `IOCAH10R-22T`,
    price: 1550,
    priceDisplay: null,
    phase: `Three`,
    power: `22 kW`,
    ratedCurrent: `32A`,
    countryOfManufacture: `China`,
    dimensions: `269 x 360 x 146 mm`,
    weight: `7.6 kg`,
    cableLength: `5 meters`,
    display: `Yes`,
    solarSmart: true,
    internetConnection: true,
    appControl: true,
    ocppCompatible: true,
    loadManagement: false,
    phaseSwitching: false,
    multiUser: true,
    ipRating: `IP55`,
    operatingTemp: `-30°C to +50°C`,
    bidirectional: false,
    warrantyYears: `2 years`,
    chargingModes: `Solar-only, Solar Assist, Fast`,
    notes: `Includes CT clamps for measuring solar excess. All-in-one solar, load management and app control. Distributed by EVSE Australia, established since 2016.`,
  },
];
